fragment CourseFragment on Course {
  id
  title
  description
  price
  discount
  banner {
    ...MediaFragment
  }
  exams {
    ...ExamFragment
  }
  subjects {
    ...SubjectsFragment
  }
  tariff {
    ...TariffFragment
  }

  kinescopeVideos {
    ...Kinescope_Video_Fragment
  }
}
