query GetNotCorrectedAnswers($userId: JSON) {
  TestResults(where: { user: { equals: $userId }, answers__isCorrect: { equals: false } }) {
    docs {
      answers {
        question {
          questionText

          recommendation {
            id
          }
        }

        isCorrect
      }
    }
  }
}

query GetRecommendationsByIds($where: Recomendation_where) {
  Recomendations(where: $where) {
    docs {
      id
      title
      description
    }
  }
}

query GetRecommendationsByQuestionsIds($where: Question_where) {
  Questions(where: $where) {
    docs {
      questionText
      id

      recommendation {
        id
      }
    }
  }
}

query GetRecommendationsByQuestionsIDS2($questionsIds: [String!]!) {
  GetRecommendationsByQuestionsIDS(answerIds: $questionsIds) {
    questionId
    questionText
    recommendation {
      id
      title
      description
    }
  }
}
