query GetAllTests($limit: Int, $page: Int, $examId: JSON, $subjectId: JSON) {
  Tests(
    where: { exam: { equals: $examId }, subjects: { equals: $subjectId } }
    limit: $limit
    page: $page
  ) {
    docs {
      ...TestFragment
    }

    page
    totalPages
    totalDocs
  }
}

query GetAllUserTests(
  $userId: Int!
  $status: TestResult_Status_ALL
  $examId: Int
  $subjectId: Int
) {
  GetUserTests(userId: $userId, status: $status, examId: $examId, subjectId: $subjectId) {
    docs {
      id
      title
      description
      status
    }

    page
    totalPages
    totalDocs
  }
}
