query GetAllTestsByTitles {
  Tests {
    docs {
      id
      title
    }
  }
}

query GetAllUserTests($userId: Int, $status: TestResult_Status_ALL, $examId: Int, $subjectId: Int) {
  GetUserTests(userId: $userId, status: $status, examId: $examId, subjectId: $subjectId) {
    docs {
      id
      title
      description
      status
    }

    page
    totalPages
    totalDocs
  }
}
