query GetByIdTest($id: Int!) {
  Test(id: $id) {
    ...TestFragment
  }
}

query GetTestsByIds($limit: Int, $page: Int, $examId: JSON, $subjectId: JSON) {
  Tests(
    where: { exam: { equals: $examId }, subjects: { equals: $subjectId } }
    limit: $limit
    page: $page
  ) {
    docs {
      ...TestFragment
    }

    page
    totalPages
    totalDocs
  }
}
