query GetByIdTest($id: Int!) {
  Test(id: $id) {
    ...TestFragment
  }
}

query GetTestsByIds(
  $or: [Test_where_or!]!
  $limit: Int
  $page: Int
  $examId: JSON
  $subjectId: JSON
) {
  Tests(
    where: { OR: $or, exam: { equals: $examId }, subjects: { equals: $subjectId } }
    limit: $limit
    page: $page
  ) {
    docs {
      ...TestFragment
    }

    page
    totalPages
    totalDocs
  }
}
