query GetCourseBySlug($slug: String) {
  Courses(where: { slug: { equals: $slug } }) {
    docs {
      ...CourseFragment

      kinescopeVideos {
        ...Kinescope_Video_Fragment
        test {
          id
          title
        }
      }
    }
  }
}
