import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/shared/assets/css/globals.css";
import { Providers } from "@/shared/providers/providers";

const geistSans = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
