import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/shared/assets/css/globals.css";
import { Providers } from "@/shared/providers/providers";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="h-full">
      <body className={`${geistSans.variable} h-full min-h-screen antialiased`}>
        <ClerkProvider
          publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        >
          <Providers>{children}</Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
