import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/shared/assets/css/globals.css";
import { Providers } from "@/shared/providers/providers";
import { AppFooter } from "@/widgets/app-footer";

const geistSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="h-full">
      <body className={`${geistSans.variable} h-full min-h-screen antialiased`}>
        <Providers>
          {children}

          <AppFooter />
        </Providers>
      </body>
    </html>
  );
}
