query GetAllWebinars {
  Webinars(limit: 100, where: { endAt: { greater_than: "${new Date().toISOString()}" } }) {
    docs {
      id
      title
      type
      startsAt
      endAt
      slug
    }
  }
}
