query GetAllWebinars($now: DateTime!) {
  Webinars(limit: 100, where: { endAt: { greater_than: $now } }) {
    docs {
      id
      title
      type
      startsAt
      endAt
      slug
    }
  }
}
