query GetWebinarPaymentByUserId($userId: JSON, $webinarId: JSON) {
  WebinarPayments(
    where: {
      user: { equals: $userId }
      webinar: { equals: $webinarId }
      status: { equals: succeeded }
    }
  ) {
    docs {
      webinar {
        id
        url
      }
    }
  }
}

query GetWebinarByPaymentId($paymentId: String) {
  WebinarPayments(where: { paymentId: { equals: $paymentId } }) {
    docs {
      id
    }
  }
}

mutation CreateWebinarPayment($data: mutationWebinarPaymentInput!) {
  createWebinarPayment(data: $data) {
    id
  }
}

mutation UpdateWebinarPayment($id: Int!, $data: mutationWebinarPaymentUpdateInput!) {
  updateWebinarPayment(id: $id, data: $data) {
    id
  }
}
