query GetWebinarPaymentByUserId($userId: JSON, $webinarId: JSON) {
  WebinarPayments(
    where: {
      user: { equals: $userId }
      webinar: { equals: $webinarId }
      status: { equals: succeeded }
    }
  ) {
    docs {
      webinar {
        id
        url
      }
    }
  }
}

query GetWebinarPaymentByUser($userId: JSON) {
  WebinarPayments(
    where: { user: { equals: $userId }, status: { equals: succeeded } }
    limit: 1000
  ) {
    docs {
      webinar {
        id
        url
        title
        startsAt
        slug
        endAt
      }
    }
  }
}

query GetWebinarByPaymentId($paymentId: String) {
  WebinarPayments(where: { paymentId: { equals: $paymentId } }) {
    docs {
      id
    }
  }
}

mutation CreateWebinarPayment($data: mutationWebinarPaymentInput!) {
  createWebinarPayment(data: $data) {
    id
  }
}

mutation UpdateWebinarPayment($id: Int!, $data: mutationWebinarPaymentUpdateInput!) {
  updateWebinarPayment(id: $id, data: $data) {
    id
  }
}

query WebinarSuccessCount($id: JSON) {
  WebinarPayments(where: { webinar: { equals: $id }, status: { equals: succeeded } }, limit: 1000) {
    totalDocs
  }
}

query GetInfoWebinarPaymentsByWebinarId($webinarId: JSON) {
  WebinarPayments(
    where: { webinar: { equals: $webinarId }, status: { equals: succeeded } }
    limit: 1000
  ) {
    docs {
      id

      user {
        email
        name
      }

      createdAt
    }
  }
}
