query GetPurchaseById($userId: JSON, $courseId: JSON) {
  Purchases(where: { user: { equals: $userId }, course: { equals: $courseId } }) {
    docs {
      id
      pricePaid
      user {
        email
        id
      }
      tariff {
        id
        title
        price
      }
    }
  }
}
