mutation CreateUser(
  $email: String!
  $password: String!
  $role: User_role_MutationInput!
  $signupMethod: User_signupMethod_MutationInput!
  $name: String
) {
  createUser(
    data: {
      email: $email
      password: $password
      role: $role
      signupMethod: $signupMethod
      name: $name
    }
  ) {
    id
    email
    isVerified
  }
}

query GetUserByEmail($email: EmailAddress!) {
  Users(where: { email: { equals: $email } }) {
    docs {
      id
      email
      password
      signupMethod
      role
      isVerified

      name
      avatar {
        ...MediaFragment
      }
    }
    totalDocs
  }
}

mutation UpdateUserEmail($id: Int!, $email: String) {
  updateUser(id: $id, data: { email: $email }) {
    id
    email
  }
}

mutation UpdateUserPassword($id: Int!, $password: String) {
  updateUser(id: $id, data: { password: $password }) {
    id
    email
  }
}

mutation UpdateUserVerified($id: Int!) {
  updateUser(id: $id, data: { isVerified: true }) {
    id
    email
  }
}
