mutation LoginUser($email: String!, $password: String!) {
  loginUser(email: $email, password: $password) {
    user {
      id
      email
    }
  }
}

mutation CreateUser(
  $email: String!
  $password: String!
  $role: User_role_MutationInput!
  $signupMethod: User_signupMethod_MutationInput!
) {
  createUser(
    data: { email: $email, password: $password, role: $role, signupMethod: $signupMethod }
  ) {
    id
  }
}

query GetUserByEmail($email: EmailAddress!) {
  Users(where: { email: { equals: $email } }) {
    totalDocs
    docs {
      id
      email
      role
      signupMethod
    }
  }
}
