query GetHomePage {
  HomePage {
    mainOfferBanner {
      title
      description
      label
      options {
        text
        id
      }
    }

    aboutProjectBanner {
      title
      subtitle
      content

      media {
        ...MediaFragment
      }
    }

    diagnosticTestBanner {
      title
      subtitle
      label
    }

    featuredTest {
      ...TestFragment
    }
  }
}
