query GetHomePage {
  HomePage {
    Meta {
      seo_title
      seo_description
    }

    mainOfferBanner {
      title
      description
      label
      options {
        text
        id
      }
    }

    aboutProjectBanner {
      title
      subtitle
      description

      media {
        ...MediaFragment
      }
    }

    diagnosticTestBanner {
      title
      subtitle
    }

    featuredTest {
      ...TestFragment
    }
  }
}
