query GetPostList($limit: Int!, $page: Int!) {
  Posts(limit: $limit, page: $page, where: { _status: { equals: published } }) {
    docs {
      id
      slug
      title
      image {
        id
        alt
        url
      }
      categories {
        title
      }
    }
    hasNextPage
    hasPrevPage
    limit
    nextPage
    page
    pagingCounter
    prevPage
    totalDocs
    totalPages
  }
}
