import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './../../shared/assets/css/globals.css'
import { Providers } from '@/shared/providers/providers'
import { SessionProvider } from 'next-auth/react'
const geistSans = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru" className="h-full">
      <body className={`${geistSans.variable} flex min-h-screen flex-col antialiased`}>
        <SessionProvider>
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  )
}
